targets:
  $default:
    builders:
      drift_dev:
        options:
          # Configuration pour la génération de code Drift
          generate_connect_constructor: true
          generate_connect_constructor_on_queries: true
          generate_connect_constructor_on_database: true
          generate_connect_constructor_on_dao: true
          generate_connect_constructor_on_views: true
          generate_connect_constructor_on_triggers: true
          generate_connect_constructor_on_indexes: true
          generate_connect_constructor_on_views: true
          generate_connect_constructor_on_triggers: true
          generate_connect_constructor_on_indexes: true
